version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: comic-mongodb
    ports:
      - "27017:27017"
    networks:
      - comic-network

  rabbitmq:
    image: rabbitmq:3.11-management-alpine
    container_name: comic-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - comic-network

  krakend:
    image: devopsfaith/krakend
    container_name: comic-krakend
    ports:
      - "8080:8080"
    volumes:
      - ${PWD}/gateway:/etc/krakend/
    command: [ "sh", "-c", "while ! nc -z comic-rabbitmq 5672; do sleep 1; done && /usr/bin/krakend run -d -c /etc/krakend/docker-db.json" ]
    depends_on:
      - rabbitmq
    networks:
      - comic-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  comic-network:
